language: bash
services: docker

branches:
  except:
  - master

env:
  - VARIANT=php7.3/apache
  - VARIANT=php7.3/fpm
  - VARIANT=php7.4/apache
  - VARIANT=php7.4/fpm
  - VARIANT=php8.0/apache
  - VARIANT=php8.0/fpm

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VARIANT"
  - slash='/'; tag="${VARIANT//$slash/-}"; image="tfirdaus/wp-stack:$tag"

script:
  - travis_retry docker build -t "$image" .

after_script:
  - docker images
  - docker run "$image" /bin/sh -c "php -m | grep redis"

# vim:set et ts=2 sw=2:
